### ISSUE TITLE
感谢大佬的分享

### ISSUE THREAD

**Issue by HuaZaiWuDi** [RuffianZhong/RWidgetHelper#10]
之前一直在找能替代drawable的的控件，试了几种方式都不是很好，
https://github.com/JavaNoober/BackgroundLibrary 这种是全局替换的方式
https://github.com/duanhong169/DrawableToolbox 这种是KT动态设置的，都不是很理想。
我现在使用的是QMUIAndroid 的实现，但是这个可扩展性小，竟然没有点击状态的设置。
他们共同的有点就是侵入小。但是都有一些难以忍受的缺点。。所以选择了大佬的方式。
现在在大佬的基础上面加入了Ripple和渐变色的实现，都是一些比较简单的实践。有时间把阴影的实现加入。
总之感谢大佬了

**Comment by RuffianZhong** [comment]
@HuaZaiWuDi 
兄台言重了，开源就是为了共同进步和方便开发
可以的话帮忙推广一下呀，您的start是对我最大的鼓励
