### ISSUE TITLE
androidx v0.0.6 RTextView闪退

### ISSUE THREAD

**Issue by android-1995** [RuffianZhong/RWidgetHelper#100]
![image](https://user-images.githubusercontent.com/35674533/134306389-222b5291-1815-4605-86d7-120d166a498e.png)
测试机为SDK版本19

**Comment by RuffianZhong** [comment]
@android-1995 麻烦把布局代码贴一下

**Comment by android-1995** [comment]
> @android-1995 麻烦把布局代码贴一下

demo的代码在19的模拟器打开就闪退

**Comment by RuffianZhong** [comment]
@android-1995 抱歉v0.0.6代码修改不当导致在低版本出现崩溃的问题，并且没有测试覆盖到，0.0.7版本已经修复

**Comment by android-1995** [comment]
> @android-1995 抱歉v0.0.6代码修改不当导致在低版本出现崩溃的问题，并且没有测试覆盖到，0.0.7版本已经修复

![image](https://user-images.githubusercontent.com/35674533/134751657-4be75180-7d68-42cf-8c57-1875f2452f22.png)
AndroidX的0.0.7失败了

**Comment by android-1995** [comment]
@RuffianZhong

**Comment by RuffianZhong** [comment]
@android-1995 应该是 jitpack 出了问题，已经升级到0.0.8版本
