### ISSUE TITLE
RTextView在列表里无法响应点击事件的问题

### ISSUE THREAD

**Issue by harryhasai** [RuffianZhong/RWidgetHelper#105]
如果是在Adapter里面自己为RTextView设置点击事件, 在写一个回调监听, 在Activity里面set这个监听, 这种方式是可以响应的,
但是问题是我用的是BaseQuickAdapter , 直接add了子View的id进去, 然后在统一的setOnChildClickListener里面无法响应该监听事件, 但是如果吧RtextView换成TextView就可以了

**Comment by harryhasai** [comment]
> @harryhasai 还有这种事，上代码我看下

大概的基础布局是Activity里面有4个fragment, 然后某一个fragment里面还有4个fragment
然后最里层的fragment的布局是这样的
![image](https://user-images.githubusercontent.com/28555314/156298150-fbea3d8e-ca18-4481-ade3-6953997ca1aa.png)
然后adapter_item的布局是这样的
![image](https://user-images.githubusercontent.com/28555314/156298254-f5b2dd95-64eb-48c5-a717-c52dac983e52.png)
我画红框的两个TextView原来是Rtextview,

**Comment by harryhasai** [comment]
> @harryhasai 还有这种事，上代码我看下

别的也没啥特殊的复杂的嵌套逻辑,, 就是一个普通的item,, 之前用你RTextView那个库的时候也没发现这种情况, 这次换成这个库之后就出来了......

**Comment by RuffianZhong** [comment]
@harryhasai 仔细看了一圈代码，库里面也没有什么骚操作。
这个是在所有RV+BaseQuickAdapter搭配的简单场景下也无法响应事件吗？ 
另外一点，本库的其他版本可以使用，最新版本有问题？
实在找不到突破口了，麻烦提供以上信息，方便我进一步调查

**Comment by harryhasai** [comment]
com.github.RuffianZhong:RWidgetHelper:androidx.v0.0.8 这个是我使用的版本, 应该是最新的, 
我刚才又试了一下, 很奇怪 又可以了, 我试着用你的app:background_normal 设置背景和系统的android:background都设置了. 发现又可以了.... 很诡异. kt里面的代码我基本没有动, 唯一改动的就是把布局换回了TextView, 然后自己写了shape.
 有点复现不了我当时的情况了, 我在看一下吧 , 如果能复现我会及时在这里反馈给你的. 
谢谢大佬百忙之中能抽空看我提的问题,,(●´З｀●)
