### ISSUE TITLE
能不能搞个APKdemo装下  源码都没升级Androidx 全报错 版本太低无法跑起来

### ISSUE THREAD

**Issue by xuxinjiang** [RuffianZhong/RWidgetHelper#106]

**Comment by RuffianZhong** [comment]
@xuxinjiang 切到 master.androidX 分支看看

<img width="362" alt="image" src="https://user-images.githubusercontent.com/7261019/164662106-e8ba16a4-5b29-40ba-a762-20bc6e63d97f.png">
