### ISSUE TITLE
shadow阴影大小对View真实尺寸的换算规则？

### ISSUE THREAD

**Issue by scsfwgy** [RuffianZhong/RWidgetHelper#108]
一般UI给的图的尺寸是不包含阴影的，阴影是单独给的。但是我们画View时尺寸是带阴影大小的。这个换算关系是如何？
比如不带阴影View：宽100，高200。阴影设置一下属性：

       <item name="shadow_dx">4dp</item>
        <item name="shadow_dy">2dp</item>
        <item name="shadow_radius">10dp</item>

那么真实View的宽高各是多少？

宽：108  高：204？我看样式好像是不对的。

**Comment by RuffianZhong** [comment]
![image](https://user-images.githubusercontent.com/7261019/195782915-5d19885e-08bf-4a3c-98d2-5ccff47258d0.png)

1. 设置 shadow_radius=20dp 相当于背景周边会 padding=20dp 的大小用来完整展示阴影。

2.设置 `app:shadow_dx="5dp" / app:shadow_dy="5dp"` 则会在 *1* 的基础上在 水平/垂直 方向 再 padding=5dp 的大小用来完整展示阴影
