### ISSUE TITLE
作为recyclerview item 跟布局时显示空白

### ISSUE THREAD

**Issue by XuJhin** [RuffianZhong/RWidgetHelper#109]
当item的高度超过一屏，使用作为跟布局会导致页面不显示item

**Comment by RuffianZhong** [comment]
@XuJhin 麻烦提供多一点信息，哪个组件，使用了什么特性导致不限空白？如果替换成原生组件呢？

**Comment by RuffianZhong** [comment]
@XuJhin 应该是使用了阴影时超过一屏高度出现的空白问题吧？

新版本 androidx.v0.0.11 / support.v0.0.11 已修复
