### ISSUE TITLE
RImageView能否支持显示gif?

### ISSUE THREAD

**Issue by yunshu37** [RuffianZhong/RWidgetHelper#11]
XML直接加载gif图片似乎是不会动的,尺寸也出现了问题

**Comment by RuffianZhong** [comment]
@yunshu37 
现在这个RImageView是不支持xml直接加载gif的，因为现在很多图片加载框架例如Glide都有这些功能，就没有再花时间去实现了

**Comment by yunshu37** [comment]
> @yunshu37
> 现在这个RImageView是不支持xml直接加载gif的，因为现在很多图片加载框架例如Glide都有这些功能，就没有再花时间去实现了



> @yunshu37
> 现在这个RImageView是不支持xml直接加载gif的，因为现在很多图片加载框架例如Glide都有这些功能，就没有再花时间去实现了

**Comment by yunshu37** [comment]
好的,谢谢.确实这个自己处理一下就好了,作者写的控件很好用,感谢!
