### ISSUE TITLE
Android Studio Chipmunk xml preview

### ISSUE THREAD

**Issue by IamIan2020** [RuffianZhong/RWidgetHelper#112]
Android Studio Chipmunk 布局不能预览了

**Comment by IamIan2020** [comment]
用 RImageView  布局不能预览

**Comment by xuxinjiang** [comment]
你解决了这个问题吗

**Comment by RuffianZhong** [comment]
@IamIan2020 @xuxinjiang 我更新了AS确实发现存在不能预览的问题，看了一下，暂时没有头绪怎么去适配AS的新特性。
简单看了一下，AS带来的问题，一定是会影响众多的自定义view不能预览，建议暂时使用老版本AS

当然，本库肯定存在语法或者编码问题导致AS上不能预览，我会再跟进一下，找找适应AS的方式

**Comment by xuxinjiang** [comment]
> @IamIan2020 @xuxinjiang 我更新了AS确实发现存在不能预览的问题，看了一下，暂时没有头绪怎么去适配AS的新特性。 简单看了一下，AS带来的问题，一定是会影响众多的自定义view不能预览，建议暂时使用老版本AS
> 
> 当然，本库肯定存在语法或者编码问题导致AS上不能预览，我会再跟进一下，找找适应AS的方式

感谢回复，期待大佬更新维护，这个库已经上万Android开发者在使用了，越来越好用，目前是最牛的AndroidUI控件框架，强烈推荐使用。感谢大佬的无私奉献精神

**Comment by RuffianZhong** [comment]
@IamIan2020 @xuxinjiang 

不好意思，我来晚了。更新到最新版本，已经修复 Android studio 的预览
