### ISSUE TITLE
新版2021.3.1，Android Studio Chipmunk 布局不能预览了

### ISSUE THREAD

**Issue by xuxinjiang** [RuffianZhong/RWidgetHelper#113]
![image](https://user-images.githubusercontent.com/41047773/192074726-5c9f1a5f-0e22-4479-85f8-c7a4793ca930.png)
![image](https://user-images.githubusercontent.com/41047773/192074735-edb68b4f-5ab8-4a37-967d-dc9b4f8132f5.png)
去掉自定义com.ruffian.library.widget.RImageView 才能预览 
作者赶紧解决一下这个问题吧

**Comment by tanranran** [comment]
AS的BUG

**Comment by RuffianZhong** [comment]
[issues#114](https://github.com/RuffianZhong/RWidgetHelper/issues/114)
