### ISSUE TITLE
新版 studio 2021.3.1版本  无法预览xml界面 demo也是一样

### ISSUE THREAD

**Issue by xuxinjiang** [RuffianZhong/RWidgetHelper#114]
![image](https://user-images.githubusercontent.com/41047773/192082774-1356b676-50a9-40a5-843b-6f24fbc18449.png)

**Comment by tanranran** [comment]
这个是AS的BUG

**Comment by xuxinjiang** [comment]
> 这个是AS的BUG

你确定？ 你那边也是吗

**Comment by xuxinjiang** [comment]
![image](https://user-images.githubusercontent.com/41047773/192237448-81b658d0-4eb5-4c05-b00f-397cf8210cfc.png)
![image](https://user-images.githubusercontent.com/41047773/192237485-e8767c43-3250-4dca-bfb8-055373969631.png)
加上com.ruffian.library.widget.RImageView无法预览了

**Comment by hewh7** [comment]
请问有谁解决了吗? Android Studio Electric Eel | 2022.1.1也有同样的问题, 视图无法预览很麻烦, 总不能每次都注释控件去看预览吧

**Comment by harryhasai** [comment]
> 请问有谁解决了吗? Android Studio Electric Eel | 2022.1.1也有同样的问题, 视图无法预览很麻烦, 总不能每次都注释控件去看预览吧

同样 更新了2个新版本了 还是无法预览.. 愁人啊

**Comment by RuffianZhong** [comment]
@tanranran @harryhasai @hewh7 @xuxinjiang 
不好意思，我来晚了。更新到最新版本，已经修复 Android studio 的预览

**Comment by harryhasai** [comment]
> @tanranran @harryhasai @hewh7 @xuxinjiang 不好意思，我来晚了。更新到最新版本，已经修复 Android studio 的预览

貌似还是不行 我刚试了一下. AndroidStudio 版本是Android Studio Electric Eel | 2022.1.1 Patch 1 RImageView还是无法预览 重新加载了Gradle 而且重新Rebuild了 也还是不行

**Comment by harryhasai** [comment]
![image](https://user-images.githubusercontent.com/28555314/220246420-79ee7f6a-1b93-4624-a62c-263fd0bbe72f.png)
![image](https://user-images.githubusercontent.com/28555314/220246443-14372bcc-af48-4a78-ba14-b65c6f756282.png)
如图所示, 注释掉就出来了, 版本也更新到0.0.12了

**Comment by harryhasai** [comment]
大佬抽空也可以看一下 麻烦大佬了, 谢谢大佬了!

**Comment by hewh7** [comment]
> @tanranran @harryhasai @hewh7 @xuxinjiang 不好意思，我来晚了。更新到最新版本，已经修复 Android studio 的预览

我也是, 依赖更新到0.0.12了, 甚至Invalidate cache也还是不能预览

**Comment by RuffianZhong** [comment]
@harryhasai @hewh7 

android studio 这个更新真的很无语呀。
上午我用的是 Android Studio Chipmunk | 2021.2.1 Patch 1 调试的，各个组件都能正常预览
下午重新下载 Android Studio Electric Eel | 2022.1.1 Patch 1 调试，发现 RImageView 无法预览

现在升级到最新版本 v0.0.13 就都可以预览了！童叟无欺

**Comment by hewh7** [comment]
> @harryhasai @hewh7
> 
> android studio 这个更新真的很无语呀。 上午我用的是 Android Studio Chipmunk | 2021.2.1 Patch 1 调试的，各个组件都能正常预览 下午重新下载 Android Studio Electric Eel | 2022.1.1 Patch 1 调试，发现 RImageView 无法预览
> 
> 现在升级到最新版本 v0.0.13 就都可以预览了！童叟无欺

可以了, 大佬牛逼orz

**Comment by harryhasai** [comment]
> @harryhasai @hewh7
> 
> android studio 这个更新真的很无语呀。 上午我用的是 Android Studio Chipmunk | 2021.2.1 Patch 1 调试的，各个组件都能正常预览 下午重新下载 Android Studio Electric Eel | 2022.1.1 Patch 1 调试，发现 RImageView 无法预览
> 
> 现在升级到最新版本 v0.0.13 就都可以预览了！童叟无欺

可以显示了, 就是想问一下大佬怎么解决的, 我自己自定义View也不显示,, 大佬那里有没有链接, 能不能发出来让我学习一下..

**Comment by RuffianZhong** [comment]
> > @harryhasai @hewh7
> > android studio 这个更新真的很无语呀。 上午我用的是 Android Studio Chipmunk | 2021.2.1 Patch 1 调试的，各个组件都能正常预览 下午重新下载 Android Studio Electric Eel | 2022.1.1 Patch 1 调试，发现 RImageView 无法预览
> > 现在升级到最新版本 v0.0.13 就都可以预览了！童叟无欺
> 
> 可以显示了, 就是想问一下大佬怎么解决的, 我自己自定义View也不显示,, 大佬那里有没有链接, 能不能发出来让我学习一下..

你可以打开我的源代码，然后搜索“Android studio预览”每一处导致不能预览的地方和解决方案都有注释

**Comment by harryhasai** [comment]
谢谢大佬 我看一下
