### ISSUE TITLE
com.ruffian.library.widget.RImageView 导致AS无法预览布局的情况，去掉就能预览

### ISSUE THREAD

**Issue by xuxinjiang** [RuffianZhong/RWidgetHelper#116]
![image](https://user-images.githubusercontent.com/41047773/192934356-312540c5-c2b0-4325-82a4-1e58686026cc.png)
![image](https://user-images.githubusercontent.com/41047773/192934372-18d93eba-ed47-4f83-83a0-641ede189024.png)

**Comment by RuffianZhong** [comment]
[issues#114](https://github.com/RuffianZhong/RWidgetHelper/issues/114)
