### ISSUE TITLE
背景颜色 按下 不支持图片么 ？

### ISSUE THREAD

**Issue by baowenqing** [RuffianZhong/RWidgetHelper#12]
代码里现在只支持 颜色和颜色的数组  不支持图片资源吗

**Comment by RuffianZhong** [comment]
@baowenqing 
现在不支持背景是图片资源。支持是颜色和渐变颜色

**Comment by RuffianZhong** [comment]
@baowenqing 
来迟了，更新版本到 1.0.4 背景已经支持 drawable/mipmap
