### ISSUE TITLE
setBackgroundColorNormal 失效

### ISSUE THREAD

**Issue by YUHAN-GUO** [RuffianZhong/RWidgetHelper#121]
版本是最新的androidx分支
在布局里用backgroundColorArray  在代码里修改成 backgroundColor 会失效
<img width="776" alt="image" src="https://user-images.githubusercontent.com/43516357/231711584-9fe7e03d-f10c-45c0-948c-e79cdfcae53a.png">
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/43516357/231711704-834359cf-9c46-4656-bc3c-0cdf71bbc8e0.png">

**Comment by RuffianZhong** [comment]
v0.0.14 版本已经修复此问题，升级版本可以解决
