### ISSUE TITLE
setBackgroundColorNormalArray

### ISSUE THREAD

**Issue by AlceZhang** [RuffianZhong/RWidgetHelper#122]
请问下，如何动态代码设置setBackgroundColorNormalArray？
如下设置无效，方式不对，还是其他?
val array=context.resources.obtainTypedArray(com.example.lib_common.R.array.array_l_r)
            val len = array.length()
            val itemBg = IntArray(len)
            for (i in 0 until len) {
                itemBg[i] = array.getResourceId(i, 0)
            }
 backgroundColorNormalArray = itemBg

**Comment by wananxin** [comment]
.helper.setBackgroundColorNormalArray(this.resources.getIntArray(R.array.color_array_white))
