### ISSUE TITLE
希望再添加一种selected状态

### ISSUE THREAD

**Issue by liweiGe** [RuffianZhong/RWidgetHelper#14]
希望再添加一种selected状态,这个状态也是比价常用的,另外这个任何一个view都有的属性

**Comment by liweiGe** [comment]
目前只有unable,press和正常状态

**Comment by RuffianZhong** [comment]
@liweiGe 麻烦你说明一下是哪个状态呢？
![image](https://user-images.githubusercontent.com/7261019/47480426-f1cdef80-d862-11e8-8fbe-6e0f5fab8187.png)
或者是什么样的效果，使用场景？

**Comment by liweiGe** [comment]
写selector 时候不是会有 android:state_selected="true" ,后面写相应被选中后的颜色或者是图片,就这个状态跟 android:state_enabled="true"  android:state_pressed 这几个状态一样,再加一个状态selected状态

xml 里就可以直接写app:icon_src_selected="xxx"

**Comment by RuffianZhong** [comment]
@liweiGe 
升级到 1.0.4 我新增了    check状态（背景、文字颜色），对应控件 RCheckBox  RRadioButton
