### ISSUE TITLE
希望添加ripple的水波纹效果以及阴影背景效果

### ISSUE THREAD

**Issue by supercwn** [RuffianZhong/RWidgetHelper#16]

**Comment by supercwn** [comment]
还有个怎么设置TextView背景图片的？当我设置rtv:background_normal="@drawable/shape_oval"出现了错误

**Comment by scsfwgy** [comment]
+1,水波纹还是很有需要的

**Comment by RuffianZhong** [comment]
@supercwn @scsfwgy 
久等了，1.1.1版本已经加上了水波纹效果。欢迎使用，有问题可以提issue

**Comment by scsfwgy** [comment]
@RuffianZhong 

6666，水波纹效果很好

> ripper 效果和 pressed/unable/checked 对立，启用 ripper 后，这三种状态无效果

启动ripper后按压效果不起效可以理解，其实水波纹就是变相的按压效果。但是unable这种效果还是有需要的，比如登录中，在请求过程中不允许点击。

**Comment by RuffianZhong** [comment]
@scsfwgy 
恩恩，unable这个问题当时也考虑到了，我怕等我完美解决的时候又不知道拖到了什么时候，赶紧先上线了，后面优化

**Comment by scsfwgy** [comment]
辛苦辛苦

**Comment by RuffianZhong** [comment]
@scsfwgy 更新到1.1.2版本，已经支持与 unable / checked 状态兼容，同时修改名称 ripper -> ripple

**Comment by RuffianZhong** [comment]
@supercwn 
最新版V 1.1.3 已经支持 阴影效果，欢迎使用。

**Comment by scsfwgy** [comment]
666,高产
