### ISSUE TITLE
可以给一个布局设置像cardView一样的背景四周带有阴影的效果吗？

### ISSUE THREAD

**Issue by chenxiaofei910714** [RuffianZhong/RWidgetHelper#18]
这个兼容版本最低到多少啊

**Comment by RuffianZhong** [comment]
@chenxiaofei910714 
CardView效果暂时没有，正在着手加入
这些功能都是基础api，使劲往下兼容没问题的

**Comment by Adaclass** [comment]
等加上阴影，估计就是万能控件了o(*￣︶￣*)o

**Comment by scsfwgy** [comment]
贼好用，牛逼。顺便提一下，是否可以给一个初始化的方法，这个初始化做什么：可以全局设置默认样式，比如按压颜色、背景色等；当然如果在使用的时候特别设置，以特别设置的为主。

**Comment by scsfwgy** [comment]
@RuffianZhong

**Comment by RuffianZhong** [comment]
@chenxiaofei910714 @Adaclass 
最新版V 1.1.3 已经支持 阴影效果，欢迎使用。
