### ISSUE TITLE
RButton如果能有一个这个就好了 主要是button的阴影效果

### ISSUE THREAD

**Issue by zmemo** [RuffianZhong/RWidgetHelper#2]
赞👍

**Comment by zhxcryptic** [comment]
@RuffianZhong 是的button的阴影边框 还有点击的button四周阴影变化的效果 
现在已经很好了 只是提一下 用着挺舒服的这个  用的最多的还是文字变色

**Comment by RuffianZhong** [comment]
@zmemo 
最新版V 1.1.3 已经支持 阴影效果，欢迎使用。
