### ISSUE TITLE
怎样通过圆角设置，来实现一个正圆？

### ISSUE THREAD

**Issue by hu70258tao** [RuffianZhong/RWidgetHelper#20]
如题

**Comment by RuffianZhong** [comment]
@hu70258tao 
一个正方形控件，圆角给到控件宽度 1/2以上就可以。如果你的控件是会动态改变大小，你可以在xml中圆角给尽可能大，比如500dp，一定是圆形

**Comment by hu70258tao** [comment]
十分感谢，昨晚搞了好久都没有做到，一直以为有个属性设置正圆。
