### ISSUE TITLE
setBackgroundDrawableNormal无效

### ISSUE THREAD

**Issue by czl0325** [RuffianZhong/RWidgetHelper#22]
代码设置一个RTextview的背景图片无效

iv1.helper.setBackgroundDrawableNormal(resources.getDrawable(R.mipmap.icon_progress_hl))

经查设置setStateBackgroundColor背景颜色是可以的，但是背景图片不行，
如果我的背景色是一张图片，怎么设置？

**Comment by RuffianZhong** [comment]
@czl0325 
现在使用的版本是多少？我记得1.0.5修复了这个问题。
还有一个问题是，现在的背景如果是图片的情况下不会有裁剪圆角的效果，就是直接设置开发者传入的资源图片

**Comment by czl0325** [comment]
1.0.5的版本
你测试下
<com.ruffian.library.widget.RTextView
            android:id="@+id/iv1"
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:layout_gravity="center"
            android:gravity="center"
            android:text="1"
            android:textColor="@android:color/white"/>

然后代码设置
iv1.helper.setBackgroundDrawableNormal(resources.getDrawable(R.mipmap.icon_progress_hl))

无效

**Comment by RuffianZhong** [comment]
@czl0325 
我测试了，可以正常显示呢。说下你的手机版本号？我这边找一下低版本的手机试试看

**Comment by czl0325** [comment]
安卓6.0的，红米Note4
