### ISSUE TITLE
RLinearLayout/RRelativeLayout 包裹子view

### ISSUE THREAD

**Issue by Superlying** [RuffianZhong/RWidgetHelper#23]
<?xml version="1.0" encoding="utf-8"?>
<com.sportq.fit.common.utils.superView.RLinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:gravity="center_horizontal"
    android:orientation="vertical"
    app:background_normal="@color/white"
    app:corner_radius="8.0dip">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:backgroud="@color/color_313131">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:layout_marginTop="15.0dip"
            android:textColor="@color/white"
            android:textSize="18.0sp" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:layout_marginBottom="18.0dip"
            android:layout_marginLeft="28.0dip"
            android:layout_marginRight="28.0dip"
            android:layout_marginTop="4.0dip"
            android:textColor="@color/color_c8c8c8"
            android:textSize="12.0sp" />
    </LinearLayout>

        <LinearLayout
            android:id="@+id/exist_cause_linear"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical" />

</com.sportq.fit.common.utils.superView.RLinearLayout>

这样布局，在dialog里面显示时，上面的圆角就没有了 是什么情况啊？

**Comment by RuffianZhong** [comment]
@Superlying 
我这边测试了一下是可以的，你在普通的布局中能正常展示圆角吗？如果可以再考虑是不是dialog使用的时候哪里有问题

**Comment by Superlying** [comment]
谢谢，我再详细的去测试看下，有啥问题的话，我再问你哈~~
