### ISSUE TITLE
background_unable无效

### ISSUE THREAD

**Issue by LLQQHH** [RuffianZhong/RWidgetHelper#25]
在xml里面设置android:enabled="false"，然后设置background_unable 无效，但是代码中设置
 RLinearLayout rLinearLayoutF = (RLinearLayout) findViewById(R.id.rLinearLayoutF);
        rLinearLayoutF.setEnabled(false);有效
![image](https://user-images.githubusercontent.com/19651932/51659220-e8306100-1fe4-11e9-8d8a-800b809d573f.png)

**Comment by LLQQHH** [comment]
原生的ViewGroup好像也有这个bug

**Comment by LLQQHH** [comment]
改成RTextView就没有问题！

**Comment by scsfwgy** [comment]
动态设置mView.setEnabled(false) view不会显示backgroundColorUnable的颜色，而是还是显示backgroundColorNormal的颜色。我看RTextViewHelpder下面的逻辑没有设置backgroundColorUnable的颜色。RBaseHelper#setup()也只是在初始化的时候设置一下。你看一下是否逻辑有问题？


` /**
     * 设置是否启用
     *
     * @param enabled
     */
    public void setEnabled(boolean enabled) {
        if (enabled) {
            if (mIconNormal != null) {
                mIcon = mIconNormal;
                setIcon();
            }
        } else {
            if (mIconUnable != null) {
                mIcon = mIconUnable;
                setIcon();
            }
        }
    }`

**Comment by scsfwgy** [comment]
@RuffianZhong

**Comment by RuffianZhong** [comment]
@scsfwgy 
您是使用的时候不能正确显示？
我测试了一下，都是能够正常使用的
`    <com.ruffian.library.widget.RLinearLayout
        android:id="@+id/view_group"
        android:layout_height="50dp"
        android:layout_width="match_parent"
        app:background_normal="@color/colorPrimary"
        app:background_pressed="@color/colorPrimaryDark"
        app:background_unable="@color/purple" />`
1.如果在代码中动态设置 直接  `mViewGroup.setEnabled(false);`
2.如果在xml中设置某个控件不可点击，则使用自定义属性（ViewGroup的特殊性，所以提供此属性）
`app:enabled="false"`

**Comment by LLQQHH** [comment]
我也可以正常使用

**Comment by scsfwgy** [comment]
我用的是RTextview,目的是:当正常时显示`app:background_normal `颜色；当正在操作时，设置.setEnabled(false)这个时候不能点击，同时显示app:background_unable的颜色。
动态设置无效。

**Comment by LLQQHH** [comment]
我是xml里面事先把不可点击的状态背景先设置好了，没有在代码里面设置

**Comment by RuffianZhong** [comment]
@scsfwgy 
正如 @LLQQHH 所说，你可以直接在xml中设置好各种状态的颜色值，在代码中只需要设置enabled=false 就好了呀，这正是使用这个控件方便之处。

同时如果你非要在代码中设置也是可以的，下面是我测试代码（测试没有问题）：
`mView.setEnabled(false);
 mView.getHelper().setBackgroundColorUnable(getResources().getColor(R.color.red));`
