### ISSUE TITLE
与glide图片加载库一起使用时placeholderBug

### ISSUE THREAD

**Issue by ZQ7** [RuffianZhong/RWidgetHelper#26]
![image](https://user-images.githubusercontent.com/18021610/51677569-0910aa80-2015-11e9-8f05-255a8810941c.png)

GlideRequest.placeholder(@DrawableRes int id)
设置占位符为色值，无法填充整个View，辛苦查看一下哪的问题~

**Comment by RuffianZhong** [comment]
@ZQ7 
已修复，升级到 1.0.8
