### ISSUE TITLE
REditView控件，数值自动追加单位问题。

### ISSUE THREAD

**Issue by hu70258tao** [RuffianZhong/RWidgetHelper#28]
你好。我现在有个功能，输入框在输入数值以后，自动后后面补一个对应的长度单位会速度单位，我是通过icon相关的几个属性来显示单位的，但是设置的hint有点长，输入数字后，数值和单位中间有很大的空隙，请问这个BUG怎么解决？

**Comment by RuffianZhong** [comment]
@hu70258tao 
我没太理解你的意思，可以提供多一点信息吗？比如效果图什么的？
理论上：这个库只是实现圆角和背景等效果。其他的都是基础控件的功能呀

**Comment by RuffianZhong** [comment]
@hu70258tao 
你所说的问题应该是drawableLeft之类的属性表现为icon和文本间距很大吧？可以试一下
`app:icon_with_text="true"` 属性为true时，文本和icon一起，再配合`drawablePadding`可以达到想要的效果
