### ISSUE TITLE
一点关于 aapt error的小建议

### ISSUE THREAD

**Issue by mmll120** [RuffianZhong/RWidgetHelper#29]
大佬你好，这里有一点点小小的建议，大佬在命名自定义属性名称的时候，可不可以在常见的类似“icon_width”这种通用名称前面加个前缀啊，因为在集成其他第三方库的时候基本都会用到这种名字，就会导致aapt编译出错，对一个刚入门的萌新来讲，aapt这种问题真的要搞爆炸了……

**Comment by RuffianZhong** [comment]
@mmll120 
这个问题我接受了，哈哈哈

**Comment by mmll120** [comment]
谢谢大佬
