### ISSUE TITLE
textview图片居中能实现吗？

### ISSUE THREAD

**Issue by 06304322** [RuffianZhong/RWidgetHelper#3]

**Comment by RuffianZhong** [comment]
@06304322 
你说的居中是不是当TV宽满屏时，内容和 drawableLeft 都居中显示？
这个不能，继承的是原生 TV 的 drawableLeft

**Comment by RuffianZhong** [comment]
@06304322 
TextView  图片和文本一起居中 
久等了，更新到1.0.5
