### ISSUE TITLE
background_pressed的不合理处

### ISSUE THREAD

**Issue by TianGuisen** [RuffianZhong/RWidgetHelper#33]
当只设置了background_normal,没有设置background_pressed,
理应按下和默认的状态是一样的,但是目前是按下的时候会变白或者说看不见了....
导致每次写background_normal我都必须再写一个一样颜色的background_pressed

**Comment by RuffianZhong** [comment]
@TianGuisen 那个控件会出现你说的这个情况，我这边处理的都是在没设置background_pressed这些状态的时候都是默认使用background_normal

**Comment by TianGuisen** [comment]
<com.ruffian.library.widget.RTextView
                android:textColor="@color/white"
                app:background_normal="@array/ff2_fe2"
                app:corner_radius="65pt"
                app:gradient_orientation="LEFT_RIGHT"/>

**Comment by RuffianZhong** [comment]
@TianGuisen 
库中逻辑是未设置其他状态背景时使用默认背景，只是其中一个判断写错了，已经修复更新。
升级到最新版本 `1.0.10`
