### ISSUE TITLE
资源定义重复

### ISSUE THREAD

**Issue by zhongzhihuashanghai** [RuffianZhong/RWidgetHelper#34]
![QQ截图20190708110656](https://user-images.githubusercontent.com/16789055/60780365-b9f8a500-a170-11e9-9875-1f54eca58d9e.png)
![QQ截图20190708110737](https://user-images.githubusercontent.com/16789055/60780367-bbc26880-a170-11e9-9162-979529075ffd.png)

运行的时候报错，资源文件的定义重复，不知道为啥，之前跑都是没有问题的，尴尬了

**Comment by RuffianZhong** [comment]
@zhongzhihuashanghai 你是升级了本库版本导致的吗？还是引入其他库之后导致的？或者会不会是AS抽风？各种build,clean,重启之类的试过了吗？这个不像是本库的问题，我一直在用没有发现这种问题
