### ISSUE TITLE
RTextView能设置选中的状态吗？checked和normal的状态

### ISSUE THREAD

**Issue by Adaclass** [RuffianZhong/RWidgetHelper#36]

**Comment by RuffianZhong** [comment]
@Adaclass 那你就应该用 `RCheckBox` 或者 `RadioButton` 你去看原生控件，也是这种继承关系，具备`checked` 状态的 TextView 就是 `RCheckBox` 或者 `RadioButton`

**Comment by RuffianZhong** [comment]
@Adaclass 
抱歉之前误解了你的意思，已经添加对应的状态，升级到 V1.1.4

**Comment by Adaclass** [comment]
...666
