### ISSUE TITLE
能加个setselect选中吗？加上选中状态就完美了

### ISSUE THREAD

**Issue by githubwxq** [RuffianZhong/RWidgetHelper#37]
能加个setselect选中吗？加上选中状态就完美了
能加个setselect选中吗？加上选中状态就完美了
能加个setselect选中吗？加上选中状态就完美了
现在缺一个选中状态

**Comment by baowenqing** [comment]
+1

**Comment by RuffianZhong** [comment]
@githubwxq @baowenqing 
已经添加，升级到 V1.1.4
