### ISSUE TITLE
阴影严重影响性能

### ISSUE THREAD

**Issue by liweiGe** [RuffianZhong/RWidgetHelper#38]
用了最新版本的阴影功能,列表滑动很卡,已经确认是阴影的问题,去掉就好了,希望修复,这个阴影功能确实很实用,希望修复

**Comment by RuffianZhong** [comment]
@liweiGe  632835821 加我QQ，想了解一下您使用情况。性能问题不允许存在

**Comment by shuaimango** [comment]
阴影功能没找到示例代码，在哪呢

**Comment by RuffianZhong** [comment]
@shuaimango 
readme中有属性介绍和代码示例呀
`
shadow_radius | 阴影大小 dp
shadow_color | 阴影颜色
shadow_dx | 阴影水平方向偏移 负数向左，正数向右 dp
shadow_dy | 阴影垂直方向偏移 负数向上，正数向下 dp
`
[demo中也有示例代码](https://github.com/RuffianZhong/RWidgetHelper/blob/master/app/src/main/res/layout/activity_shadow.xml)

**Comment by Vanish136** [comment]
+1 在列表中使用阴影导致滑动明显的卡顿感，希望作者优化下性能

**Comment by scsfwgy** [comment]
@liweiGe @Vanish136 再试试这个功能，我这边测试没问题了。。。这一块逻辑也没改。
有点邪门，和编译版本有关？

**Comment by RuffianZhong** [comment]
@LwkCoder @scsfwgy @liweiGe 
久等了，新版本 androidx.v0.0.11 / support.v0.0.11 修改了阴影的实现方式，优化了性能问题
