### ISSUE TITLE
RCheckBox 在RecyclerView 中使用出现切换图标失效

### ISSUE THREAD

**Issue by 869339820** [RuffianZhong/RWidgetHelper#39]
RecyclerView item 中使用 RCheckBox
![image](https://user-images.githubusercontent.com/32284859/64942282-3e675280-d89b-11e9-8bcf-190abe08e4a5.png)
切换了是响应点击事件相应的选中图标没替换

**Comment by 869339820** [comment]
主要问题就是实现了RCheckBox 监听事件，才会出现，不实现监听就是正常切换图标的

**Comment by RuffianZhong** [comment]
@869339820 恕我拙略，我看不懂你描述的问题。能不能详细一点？比如说你使用场景是什么，表现是怎么样的，因为在RecyclerView / ListView 这一类可以复用的view我不确定您是否正确使用了CheckBox/RadioButton 这一类控件。所以希望提供详细通俗的表述，以便我快速定位问题，修复问题

**Comment by RuffianZhong** [comment]
@869339820 
已经修复，升级到 V1.1.4

**Comment by 869339820** [comment]
6666




------------------ 原始邮件 ------------------
发件人: "Ruffian-痞子"<notifications@github.com>; 
发送时间: 2019年9月17日(星期二) 下午4:53
收件人: "RuffianZhong/RWidgetHelper"<RWidgetHelper@noreply.github.com>; 
抄送: "869339820"<869339820@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [RuffianZhong/RWidgetHelper] RCheckBox 在RecyclerView 中使用出现切换图标失效 (#39)




@869339820
 已经修复，升级到 V1.1.4
