### ISSUE TITLE
提个建议：希望能现实时预览的效果

### ISSUE THREAD

**Issue by chenyang1900** [RuffianZhong/RWidgetHelper#43]
一个非常棒的库 ，能够如果加上实时预览就更好了，Android  编译时间又长不能实时预览是一件很麻烦的事

**Comment by RuffianZhong** [comment]
@chenyang1900 
可以实时预览呀
![image](https://user-images.githubusercontent.com/7261019/65825031-89726400-e2a4-11e9-8133-5cc659d60475.png)

**Comment by chenyang1900** [comment]
![image](https://user-images.githubusercontent.com/15828867/65825126-b07d6580-e2a5-11e9-98d9-68b9b445a982.png)
不行 ，不知道是不是as的问题 我用AS 3.5  和As3.2的都无法实时查看 ；

**Comment by chenyang1900** [comment]
已解决，点击这里解决了问题
![image](https://user-images.githubusercontent.com/15828867/65825292-d4da4180-e2a7-11e9-8f2e-15fa40a5ac82.png)
