### ISSUE TITLE
clipChildren 无效

### ISSUE THREAD

**Issue by czl0325** [RuffianZhong/RWidgetHelper#48]
`
<com.ruffian.library.widget.RFrameLayout
                android:layout_width="match_parent"
                android:layout_height="100dp"
                android:layout_marginHorizontal="10dp"
                android:layout_marginTop="10dp"
                app:corner_radius="10dp"
                app:background_normal="@android:color/holo_blue_bright"
                android:clipChildren="true">

                <cn.bingoogolapple.bgabanner.BGABanner
                    android:id="@+id/banner_home"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    app:banner_pointTopBottomMargin="10dp"
                    app:banner_transitionEffect="defaultEffect"
                    app:banner_pointContainerBackground="@android:color/transparent"
                    app:banner_pageChangeDuration="1000"
                    app:banner_pointAutoPlayInterval="5000"
                    android:scaleType="fitXY"/>
            </com.ruffian.library.widget.RFrameLayout>
`

如代码，父组件com.ruffian.library.widget.RFrameLayout，设置圆角，子组件BGABanner未设置圆角，但是直角覆盖了父组件了，设置了clipChildren也无效，希望超出部分不显示，让子组件也在圆角里。

**Comment by RuffianZhong** [comment]
@czl0325 
1.首先 `clipChildren` 属性的意思是：是否限制子控件在父控件之内。
默认为true，就是我们常规看到的子控件的绘制不会超出父控件大小；
如果设置为false，则子控件大小不受父控件的限制
2.RWidgetHelper现有的控件实现的圆角都是针对于控件的背景实现圆角，并没有对子控件进行裁剪的操作。所以本库暂时是不能够实现你所描述的需求。
后续考虑实现此功能...
