### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by wayneleo** [RuffianZhong/RWidgetHelper#49]
![微信截图_20191122123913](https://user-images.githubusercontent.com/5975005/69398462-48875080-0d25-11ea-96e6-eacaf2ea3fea.png)

**Comment by RuffianZhong** [comment]
@wayneleo 抱歉给你工作带来不便。已经修复更新，升级到 v1.1.6

**Comment by wayneleo** [comment]
> @wayneleo 抱歉给你工作带来不便。已经修复更新，升级到 v1.1.6

谢谢，辛苦，继续支持！
