### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by spuermax** [RuffianZhong/RWidgetHelper#50]
![image](https://user-images.githubusercontent.com/44083470/69854353-dafa9780-12c3-11ea-8d36-55fd117fe821.png)

**Comment by spuermax** [comment]
OOM 了老哥 。

**Comment by RuffianZhong** [comment]
@spuermax  哥哥，1.1.6 版本对 RImageView 实现方式做了改进，升级版本看看？
v1.1.6　2019.11.23　 修改 RImageView 实现方式。 Fix bug

**Comment by RuffianZhong** [comment]
@spuermax 久等了，问题已经处理，请升级到 V1.1.8
