### ISSUE TITLE
Ripple NullPointerException

### ISSUE THREAD

**Issue by kobayashikanata** [RuffianZhong/RWidgetHelper#51]
RTextView上如果加了
  app:ripple_color="@color/rippleColorPrimary"
  app:ripple="true"

在9.0、10的设备上ok，在7.1的设备上报以下异常：
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.shapes.Shape android.graphics.drawable.shapes.Shape.clone()' on a null object reference
![exception](https://user-images.githubusercontent.com/19747520/69924369-fe049180-14e5-11ea-9733-07e9f5ac1af2.png)

**Comment by RuffianZhong** [comment]
@kobayashikanata 
感谢反馈，已修复。升级到V1.1.7版本
