### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by wayneleo** [RuffianZhong/RWidgetHelper#53]
用的1.1.6的，老哥
![neicunyichu](https://user-images.githubusercontent.com/5975005/70027594-7437ef80-15dd-11ea-9421-233732386deb.png)

**Comment by RuffianZhong** [comment]
@wayneleo 嗯？这些函数我在1.1.6版本上就完全移除了，用的是新的实现方式。确定使用了最新版本？
这样吧，你现在使用V1.1.7。然后告诉我你的使用场景，我这边复现一下。有什么问题请毫不犹豫的提上来

**Comment by wayneleo** [comment]
@RuffianZhong 用的v1.1.7版本，又出现了，在系统版本比较低，内存比较小的机型上，在RecyclerView列表里加载，快速滚动几页后就崩了
![微信截图_20191204173455](https://user-images.githubusercontent.com/5975005/70131317-0fec5d00-16bd-11ea-9fab-c82c1be4668a.png)

**Comment by RuffianZhong** [comment]
@wayneleo 
久等了，问题已经处理，请升级到 V1.1.8
