### ISSUE TITLE
RTextView既又图片又有文字时,图片的选中状态问题

### ISSUE THREAD

**Issue by liupeng110** [RuffianZhong/RWidgetHelper#56]
感谢作者提供的库,使用起来非常方便.提issues说一下,我遇到的问题.希望可以改善一下,让大家都参与进来一个人的力量太薄弱啦  由于我司加密环境无法直接往github提交代码,有些改动我直接贴代码了.
环境 android studio 3.5  最新版本的library库  android 7.0(5寸)和7.1.1(7寸)
相对布局中,
1.下载项目后无法跑通.没办法又自己新建个项目导入library还是无法跑通.报错ColorInt  和AppcompatResources类找不到.希望作者用最新的环境更新下库的配置。后面更新gradle导入的库然后手动把这几个类import之后正常了.
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
2.RTextView既又图片又有文字时,图片的选中状态问题
2.1 使用app:icon_src_selected 无效.(暂未找到原因)
2.2使用时发现点击需要长按才能看到状态的变化。点击一下立马松开无法看到变化,但是onClick事件已经调用.看了代码发现在处理OnTouch事件时,未处理Event.Action_Down 按下事件.改动如下：
在RTextViewHelper.onTouchEvent()函数的switch语句中增加如下代码：

 public void onTouchEvent(MotionEvent event) {
        if (!mView.isEnabled()) return;
        if (mView.isSelected()) return;
        mGestureDetector.onTouchEvent(event);
        int action = event.getAction();
        switch (action) {
            case MotionEvent.ACTION_DOWN://按下
                if (mIconPressed != null) {
                    mIcon = mIconPressed;
                    setIcon();
                }
              break;
            case MotionEvent.ACTION_UP://抬起
                if (mIconNormal != null) {
                    mIcon = mIconNormal;
                    setIcon();
                }
                break;
...
3.使用app:icon_with_text=true时,点击后 布局会乱向右边挤(暂未找到原因.)

**Comment by RuffianZhong** [comment]
@liupeng110 
谢谢你的反馈，问题解决如下，请升级到 V1.1.8
对于1是因为你的项目支持了androidX，而我的这个库没有支持，其实可以寻找解决方案的，不过我趁此机会已经迁移到androidX了。
对于2的问题中，之前我的处理是监听手势并没有在按下的时候改变图片，会稍慢一点响应。此处我接受了您的建议，修改了。
对于设置了icon_src_selected之后手势无效之前也是我在代码中做了处理，一样已经修改
**对于第3点我这边暂时没有测试到该问题，烦请您提供更详细的使用方式或示例代码**
