### ISSUE TITLE
RTextView在4.x低版本系统上设置圆角度数超过1/2时显示异常

### ISSUE THREAD

**Issue by wayneleo** [RuffianZhong/RWidgetHelper#58]
4.x上显示成这样：
![微信截图_20200311150445](https://user-images.githubusercontent.com/5975005/76391522-a7430980-63aa-11ea-9039-28acc189e4d3.png)

正确应该是这样：
![微信截图_20200311150417](https://user-images.githubusercontent.com/5975005/76391550-b1650800-63aa-11ea-836e-0729378096c1.png)

**Comment by RuffianZhong** [comment]
@wayneleo 
你设置圆角为高度的1/2即可（不要超过1/2（正方形的1/2就已经可以实现圆形了）），至于低版本上的原因暂时还未查明

**Comment by RuffianZhong** [comment]
@wayneleo 最新版本做出修改，在5.0以下版本在通过代码逻辑控制了圆角不大于高度的1/2
