### ISSUE TITLE
自定义属性冲突，没找到原因

### ISSUE THREAD

**Issue by BD1028994041** [RuffianZhong/RWidgetHelper#60]
![image](https://user-images.githubusercontent.com/8455147/76734290-996ff880-679d-11ea-9880-1bb24f787873.png)
Attribute "radius" already defined with incompatible format.

**Comment by BD1028994041** [comment]
![image](https://user-images.githubusercontent.com/8455147/76734354-bf959880-679d-11ea-90d8-a329bdbcc87c.png)

**Comment by RuffianZhong** [comment]
@BD1028994041 这个问题应该是你引入的第三方库中存在多个“radius”这个自定义属性，或者引入的第三方库和你自定义的属性都有“radius”，你查一下资料该怎么解决。我看了一下RWidgetHelper没有“radius”这个属性，都是“XXX_radius”格式的。

**Comment by zhaoxiuyu** [comment]
border_color 这个属性名称冲突了
