### ISSUE TITLE
RImageView边框和圆角问题

### ISSUE THREAD

**Issue by czl0325** [RuffianZhong/RWidgetHelper#61]
```
private void updateAttrs(Drawable drawable, ScaleType scaleType) {
        if (drawable == null) return;
        .....
}
```
RImageView在没有图片的时候，不会显示边框和圆角。这边return不合理吧，比如我是空的RimageView，点击的时候去选择照片，选好把照片填充到RImageView上，这边会导致一开始没有看到边框和圆角

**Comment by czl0325** [comment]
刚下了你的demo测试，把RImageView的src属性取消。发现边框出不来
`
            <com.ruffian.library.widget.RImageView
                android:layout_width="100dp"
                android:layout_height="100dp"
                android:layout_marginLeft="10dp"
                android:background="@color/iv_bg"
                android:scaleType="fitXY"
                app:border_color="@color/colorAccent"
                app:border_width="2dp"
                app:is_circle="true" />
`

**Comment by czl0325** [comment]
经查RFrameLayout也存在同样问题，RLinearLayout正常

**Comment by RuffianZhong** [comment]
@czl0325 
谢谢反馈，这个场景确实需要考虑，最近比较忙，我抽空会处理一下

**Comment by RuffianZhong** [comment]
@czl0325 已修改，请升级到最新版本

**Comment by czl0325** [comment]
还是没改啊？在你demo上测试的。
```
            <com.ruffian.library.widget.RImageView
                android:layout_width="100dp"
                android:layout_height="100dp"
                android:layout_marginLeft="16dp"
                android:scaleType="fitEnd"
                app:border_color="@color/colorAccent"
                app:border_width="10dp"
                app:corner_radius="10dp" />
```
你不是还是直接return了吗？
