### ISSUE TITLE
RCheckBox涟漪无效

### ISSUE THREAD

**Issue by TianGuisen** [RuffianZhong/RWidgetHelper#62]

**Comment by RuffianZhong** [comment]
@TianGuisen 描述可否详细一点：库版本，安卓版本，使用方式？
另外有一点值得一说，个人测试当中发现对于这类选中的控件如果你直接点击基本看不出水波纹效果，系统直接就选中了，如果非要看，那你可以尝试着慢慢按下去，就像remade中的动图中所示，就会有短暂的水波纹效果可以看到

**Comment by TianGuisen** [comment]
不好意思，是设置了background_normal和background_checked会无效

**Comment by RuffianZhong** [comment]
@TianGuisen 你如果认真看我上一条回复你就应该知道为什么了。因为你设置了checked当你点击的时候水波纹还没来得及展示系统就已经切换成check状态了，所以就成了你说的没有效果，你可以试着慢慢按下去，不要直接点击选中。个人认为这种情况存在的时候，水波纹没什么意义
