### ISSUE TITLE
布局中RTextView，corner_radius设置圆角后

### ISSUE THREAD

**Issue by TianGuisen** [RuffianZhong/RWidgetHelper#66]
在代码中设置.setBackgroundColor会导致圆角无效，也没有找到BackgroundNormal方法。
如何实现动态颜色变化的圆角Rtextview呢

**Comment by RuffianZhong** [comment]
@TianGuisen 有没有好好看readme的呀，你个假粉丝
![image](https://user-images.githubusercontent.com/7261019/81564223-008ae180-93ca-11ea-8703-bf4c91b27e5f.png)

**Comment by TianGuisen** [comment]
晕，之前还这样用过，突然就忘记了。。。。。
