### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by TianGuisen** [RuffianZhong/RWidgetHelper#67]
lib版本androix 0.0.3 

异常进程#线程

com.haibaoshow.youbo#main(1)

用户 ID

13858883580

发生时间

2020-05-18 19:28:34

上报时间

2020-05-18 19:28:35

应用包名

com.haibaoshow.youbo

应用版本

1.5.1

使用时长

57 秒

前后台状态

前台

设备机型

华为 LYA AL00
系统版本

Android 10,level 29

ROM

HuaWei/EMOTION

CPU架构

arm64-v8a

width and height must be > 0

com.ruffian.library.widget.RImageView.drawEmptyBitmap(RImageView.java:156)

1 android.graphics.Bitmap.createBitmap(Bitmap.java:1282)
--
2 android.graphics.Bitmap.createBitmap(Bitmap.java:1249)
3 android.graphics.Bitmap.createBitmap(Bitmap.java:1199)
4 android.graphics.Bitmap.createBitmap(Bitmap.java:1160)
5 com.ruffian.library.widget.RImageView.drawEmptyBitmap(RImageView.java:156)
6 com.ruffian.library.widget.RImageView.onDraw(RImageView.java:116)
7 android.view.View.draw(View.java:21605)
8 android.view.View.updateDisplayListIfDirty(View.java:20470)
9 android.view.View.draw(View.java:21337)
10 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
11 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
12 android.view.View.draw(View.java:21608)
13 android.view.View.updateDisplayListIfDirty(View.java:20470)
14 android.view.View.draw(View.java:21337)
15 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
16 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
17 android.view.View.updateDisplayListIfDirty(View.java:20461)
18 android.view.View.draw(View.java:21337)
19 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
20 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
21 android.view.View.updateDisplayListIfDirty(View.java:20461)
22 android.view.View.draw(View.java:21337)
23 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
24 androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
25 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
26 android.view.View.draw(View.java:21608)
27 androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
28 android.view.View.updateDisplayListIfDirty(View.java:20470)
29 android.view.View.draw(View.java:21337)
30 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
31 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
32 android.view.View.updateDisplayListIfDirty(View.java:20461)
33 android.view.View.draw(View.java:21337)
34 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
35 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
36 android.view.View.draw(View.java:21608)
37 android.view.View.updateDisplayListIfDirty(View.java:20470)
38 android.view.View.draw(View.java:21337)
39 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
40 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
41 android.view.View.updateDisplayListIfDirty(View.java:20461)
42 android.view.View.draw(View.java:21337)
43 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
44 androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
45 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
46 android.view.View.draw(View.java:21608)
47 androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
48 android.view.View.updateDisplayListIfDirty(View.java:20470)
49 android.view.View.draw(View.java:21337)
50 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
51 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
52 android.view.View.updateDisplayListIfDirty(View.java:20461)
53 android.view.View.draw(View.java:21337)
54 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
55 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
56 android.view.View.updateDisplayListIfDirty(View.java:20461)
57 android.view.View.draw(View.java:21337)
58 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
59 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
60 android.view.View.updateDisplayListIfDirty(View.java:20461)
61 android.view.View.draw(View.java:21337)
62 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
63 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
64 android.view.View.updateDisplayListIfDirty(View.java:20461)
65 android.view.View.draw(View.java:21337)
66 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
67 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
68 android.view.View.updateDisplayListIfDirty(View.java:20461)
69 android.view.View.draw(View.java:21337)
70 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
71 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
72 android.view.View.updateDisplayListIfDirty(View.java:20461)
73 android.view.View.draw(View.java:21337)
74 android.view.ViewGroup.drawChild(ViewGroup.java:4446)
75 android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
76 android.view.View.draw(View.java:21608)
77 com.android.internal.policy.DecorView.draw(DecorView.java:964)
78 android.view.View.updateDisplayListIfDirty(View.java:20470)
79 android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:584)
80 android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:590)
81 android.view.ThreadedRenderer.draw(ThreadedRenderer.java:668)
82 android.view.ViewRootImpl.draw(ViewRootImpl.java:3835)
83 android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3643)
84 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2949)
85 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1852)
86 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8084)
87 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
88 android.view.Choreographer.doCallbacks(Choreographer.java:875)
89 android.view.Choreographer.doFrame(Choreographer.java:776)
90 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
91 android.os.Handler.handleCallback(Handler.java:888)
92 android.os.Handler.dispatchMessage(Handler.java:100)
93 android.os.Looper.loop(Looper.java:213)
94 android.app.ActivityThread.main(ActivityThread.java:8147)
95 java.lang.reflect.Method.invoke(Native Method)
96 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
97 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by RuffianZhong** [comment]
@TianGuisen 抱歉给你带来的不便，此问题已经修复。请升级到0.0.4
