### ISSUE TITLE
RImageView 有个严重的问题 icon_src_normal 失效啦

### ISSUE THREAD

**Issue by New-Zero-Zero** [RuffianZhong/RWidgetHelper#69]
<com.ruffian.library.widget.RImageView
        android:id="@+id/support_image"
        android:layout_width="22dp"
        android:layout_height="22dp"
        android:layout_marginRight="3dp"
        app:icon_src_normal="@mipmap/icon_zan_normal"
        app:icon_src_selected="@mipmap/icon_zan_select"
        />

app:icon_src_normal和app:icon_src_selected 没作用了。

版本 1.1.13

**Comment by RuffianZhong** [comment]
@New-Zero-Zero 
v1.1.8  版本开始修改了特性就不再支持多种状态的ImageView。只是实现默认图片的圆角

**Comment by scsfwgy** [comment]
为什么移除多种状态？我看没再继承RHelper。
有这样的需求：首页下面的四个tab,只有图片没有文字的。用RImageView会好一点，但是没有多种状态就不太好处理选中。
