### ISSUE TITLE
RTextView enabled属性布局文件初始化Bug

### ISSUE THREAD

**Issue by ZQ7** [RuffianZhong/RWidgetHelper#7]
`    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        mHelper.setEnabled(enabled);
    }`
布局文件初始化的时候mHelper为空
`    public RTextView(Context context, AttributeSet attrs) {
        mHelper = new RTextViewHelper(context, this, attrs);
        super(context, attrs); 
    }`
是否应该先初始化mHelper？

**Comment by RuffianZhong** [comment]
@ZQ7 
已经更新使用新版
