### ISSUE TITLE
REdittext高度小，里面内容显示不全

### ISSUE THREAD

**Issue by LouisKooAndroid** [RuffianZhong/RWidgetHelper#70]
大大，发现个问题，REdittext高度如果小点的话，里面输入的字会被遮住一些，显示不全，希望能有个调节输入显示区域高度的属性。

**Comment by RuffianZhong** [comment]
@LouisKooAndroid 弱弱的问一下，你是设置固定值过小导致文本显示不全吗？可否将代码贴一下？
如果是设置固定值过小导致文本显示不全，这不是常理吗？要么设置自适应高度，要么设置大一点的高度数值

**Comment by LouisKooAndroid** [comment]
<com.ruffian.library.widget.REditText
        android:id="@+id/et_value1"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="@dimen/editMargin"
        android:layout_marginTop="5dp"
        android:layout_marginEnd="@dimen/editMargin"
        android:gravity="center"
        android:paddingStart="10dp"
        android:paddingEnd="10dp"
        android:paddingTop="8dp"
        android:paddingBottom="8dp"
        android:textColor="@color/font"
        android:textColorHint="@color/fontHint"
        android:textSize="@dimen/fontSize"
        app:background_normal="@color/White"
        app:corner_radius="5dp"
        app:icon_height="20dp"
        app:icon_src_normal="@mipmap/num1"
        app:icon_width="20dp" />
好吧，我没想到，我设置自适应高度，然后用paddingTop和paddingBottom把高度撑开了。
感谢大大指导。
