### ISSUE TITLE
Edittext的text_color_selected无效

### ISSUE THREAD

**Issue by TianGuisen** [RuffianZhong/RWidgetHelper#71]
<com.ruffian.library.widget.REditText
                    android:id="@+id/et_top_price"
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:gravity="center"
                    android:hint="请输入"
                    android:background="@null"
                    android:textSize="46pt"
                    app:text_color_normal="@color/color_666666"
                    app:text_color_selected="#A37B34" />

et_top_price.isSelected=true
设置后颜色没变，textview可以

**Comment by RuffianZhong** [comment]
@TianGuisen 对于你说的情况我测试了一下。REditText 的 text_color_selected 属性并没有问题，可能是你的 REditText 正好获取了焦点，事件被 focus 抢占了（光标停在控件上时也很合理），所以 text_color_selected 设置的颜色值没有显示出来，当你焦点离开的时候就能正确显示出来了

**Comment by TianGuisen** [comment]
确实我是点点击另一个textview的时候et_top_price.isSelected=true会无效，点击另一个ecittext就可以了，但是这样的话edittext的setSelected就感觉没什么意义啊，应该setSelected方法里把焦点给操作下？

**Comment by TianGuisen** [comment]
![image](https://user-images.githubusercontent.com/19662707/88259723-70d0b000-ccf5-11ea-8fb4-611a8181e7d1.png)
![image](https://user-images.githubusercontent.com/19662707/88259748-80e88f80-ccf5-11ea-83df-69b28c2858c3.png)

一个textview一个edittext，单选，

**Comment by RuffianZhong** [comment]
@TianGuisen 不深究业务场景了，但是个人认为对于exittext而言，获取焦点一定重要过设置setSelected。我这边不会在库中直接改变和添加setSelected 函数中的逻辑，不友好。但是你可以根据业务情况 setSelected 的同时去除焦点等行为。或者换个方式实现。
顺便说一下：如果你是获取焦点的时候想要特殊颜色，你可以通过 pressed_xx 相关属性设置文本颜色，背景颜色等

**Comment by TianGuisen** [comment]
pressed不行，点其他的地方颜色就变回去了，这2个是单选必选一个。目前就用select加焦点的处理了。
