### ISSUE TITLE
oppo 中rtextview右侧有空白

### ISSUE THREAD

**Issue by TianGuisen** [RuffianZhong/RWidgetHelper#75]
![image](https://user-images.githubusercontent.com/19662707/91691918-14399e00-eb9b-11ea-9b8a-295ace5fbbca.png)
<com.ruffian.library.widget.RTextView
                        android:id="@+id/tv_msg"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginBottom="4dp"
                        android:maxLength="100"
                        android:textSize="12dp" />

**Comment by RuffianZhong** [comment]
@TianGuisen 本库版本号是多少，另外 你的布局代码就是你贴上来的这个吗？按找你贴上来的代码全部都属于安卓原生的属性，本库不会做任何处理才对

**Comment by TianGuisen** [comment]
0.0.4x，原生问题，其他手机是好的，oppo有这个问题。。

**Comment by RuffianZhong** [comment]
@TianGuisen 所以是使用原生的TextView也有问题吗

**Comment by TianGuisen** [comment]
原生的TextView也有问题

**Comment by RuffianZhong** [comment]
@TianGuisen 那这个问题不是本库引起的，你需要另寻方式去解决。
