### ISSUE TITLE
icon_normal_xxx(icon_normal_left)不支持设置gravity

### ISSUE THREAD

**Issue by scsfwgy** [RuffianZhong/RWidgetHelper#81]
icon_normal_left相关属性应该支持gravity，和TextView中gravity属性设置一致。间距通过drawablePadding控制。
@RuffianZhong

**Comment by RuffianZhong** [comment]
@scsfwgy 什么意思？使用gravity 无法在竖直方向居中吗？ icon_normal_left 跟原生控件 drawableLeft 一致默认在控件左边，使用 icon_with_text 使得图片和文本一起居中，图文间距通过 drawablePadding控制

**Comment by scsfwgy** [comment]
不好意思，没看到 icon_with_text   
#73
