### ISSUE TITLE
Demo需要自己改配置，可否配置好，拉取后直接运行即可

### ISSUE THREAD

**Issue by zqlq4ever** [RuffianZhong/RWidgetHelper#82]
![微信截图_20210225104403](https://user-images.githubusercontent.com/37474811/109095294-64fb0f80-7756-11eb-8d8f-bae12bbc24e7.png)
每次需要加入阿里云镜像，此外，也有些文件未加入 ignore。

**Comment by RuffianZhong** [comment]
@zqlq4ever 谢谢反馈，已经处理
