### ISSUE TITLE
border_width_normal和border_width_selected的bug

### ISSUE THREAD

**Issue by TianGuisen** [RuffianZhong/RWidgetHelper#86]
<com.ruffian.library.widget.RTextView
 app:border_width_normal="3dp"
        app:border_width_selected="0dp"
/>
想在选中状态没有边框，但是边框还是3dp

**Comment by RuffianZhong** [comment]
@TianGuisen 新版本已经处理，请更新，注意新版本依赖方式有改变

**Comment by RuffianZhong** [comment]
@TianGuisen support.v0.0.4/androidx.v0.0.4 版本开始修改“按下”等状态未设置时，使用默认状态的资源，开发者可以手动添加对应状态的资源。这样本库才能满足更多更广泛开发者的需求，谢谢理解
