### ISSUE TITLE
text_color_normal和text_color_selected的bug

### ISSUE THREAD

**Issue by TianGuisen** [RuffianZhong/RWidgetHelper#87]
只设置了text_color_normal=A和text_color_selected=B
但是貌似默认text_color_pressed的颜色也是和text_color_normal一样
导致如果已经是selected=true的状态下去点击，在未松开的时候颜色会由B变为A，松开后恢复为B。
期望：在没有设置text_color_pressed，按下的时候，保持当前颜色不变。

**Comment by RuffianZhong** [comment]
@TianGuisen 当前是什么状态是由系统决定的，所以目前的设计是，如果没有设置pressed等状态的值时与默认值保持一致

**Comment by RuffianZhong** [comment]
@TianGuisen 新版本已经处理，请更新，注意新版本依赖方式有改变

**Comment by RuffianZhong** [comment]
@TianGuisen support.v0.0.4/androidx.v0.0.4 版本开始修改“按下”等状态未设置时，使用默认状态的资源，开发者可以手动添加对应状态的资源。这样本库才能满足更多更广泛开发者的需求，谢谢理解
