### ISSUE TITLE
REdittext高度小，里面内容显示不全。

### ISSUE THREAD

**Issue by zhaoxiuyu** [RuffianZhong/RWidgetHelper#88]
<img width="435" alt="截屏2021-05-27 下午4 31 13" src="https://user-images.githubusercontent.com/16554580/119793316-0c7c0f80-bf09-11eb-8b48-1a2a8d13774f.png">

高度都是设置的pt_100，上面那个是REditText 显示不全，下面的EditText 可以显示全。

这是我的代码

    <com.ruffian.library.widget.REditText
        android:id="@+id/retSearch"
        android:layout_width="0dp"
        android:layout_height="@dimen/pt_100"
        android:paddingStart="@dimen/pt_10"
        android:paddingEnd="@dimen/pt_10"
        app:background_normal="@color/white"
        app:layout_constraintEnd_toStartOf="@id/ivScanCode"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <EditText
        android:layout_width="match_parent"
        android:layout_height="@dimen/pt_100"
        android:layout_marginTop="@dimen/pt_20"
        android:background="@color/white"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/retSearch" />

**Comment by zhaoxiuyu** [comment]
如果layout_height设置为wrap_content。REditText的高度是EditText两倍。

**Comment by RuffianZhong** [comment]
@zhaoxiuyu 你好，这个问题我们可以认为是安卓原生控件 EditText 存在的问题，经过我的检验，如果 EditText 设置了原生 background 属性，则会出现高度减小的现象，如果原生 EditText 不设置 background 属性则会出现高度增加的现象（以下是一个对比情况）虽然不明白为什么 EditText 会出现这种情况，但是目前似乎没有办法修改它。顺便提一句 REditText 在这方面并没有修改原生控件的任何逻辑
![image](https://user-images.githubusercontent.com/7261019/119943273-64784c00-bfc5-11eb-959a-26d09d6bcba0.png)
