### ISSUE TITLE
RXXX组件是否应该继承AppCompatXXX而非XXX？

### ISSUE THREAD

**Issue by scsfwgy** [RuffianZhong/RWidgetHelper#89]
我也是突然发现的，我这边设置的全局字体样式在RTextView无效，但是默认控件TextView就可以。
我看了一下应该就是这个父类的问题。虽然平时我们用的<TextView>,但是系统会重新指向AppCompatTextView。所以这边的组件是否都应该改一下，继承AppCompat组件？

**Comment by RuffianZhong** [comment]
@scsfwgy 已处理，support.v0.0.2/androidx.v0.0.2 开始支持
