### ISSUE TITLE
未设置IconSelected时，点击已经selected的TextView会有点问题。

### ISSUE THREAD

**Issue by wangshouz** [RuffianZhong/RWidgetHelper#94]
![image](https://user-images.githubusercontent.com/8577912/126299035-7afb32a7-1ff3-4a18-866f-f98cb5eee1bd.png)

**Comment by scsfwgy** [comment]
点击后显示的就是默认图标。这个逻辑还好吧。

**Comment by scsfwgy** [comment]
https://github.com/RuffianZhong/RWidgetHelper/issues/95

**Comment by scsfwgy** [comment]
场景：比如设置select打✔️，未设置则不显示。这样的场景未设置就不显示对应icon确实合理一点。但是还要考虑一点，不显示对应的icon的空间和间距怎么处理。
如果按照库现在的逻辑也能处理，比如未设置给一个透明的图片即可。
现在整个库大部分数据未设置都会取normal对应的值。

**Comment by RuffianZhong** [comment]
@wangshouz 你好，可以详细说一下你的使用方式和表现吗？我自测了一下好像没有什么奇怪的现象
可以的话提供一下：代码，运行效果，库版本号

**Comment by wangshouz** [comment]
就是只设置了icon_selected_left，并且有icon_with_text、drawablePadding，然后在已经是select的状态下再触摸点击，文字会发生偏移。
`
if (this.mIconLeft != null) {
  drawablePaddingHorizontal += drawablePadding;
}
`
我看着大概是select的状态下未设置icon_selected_left的时候，mIconLeft会为null，然后在绘制文字的时候drawablePadding的计算会有异常吧。

**Comment by RuffianZhong** [comment]
@wangshouz support.v0.0.4/androidx.v0.0.4 版本开始已修改
