### ISSUE TITLE
关于个别属性未设置默认取值的处理不太合理

### ISSUE THREAD

**Issue by scsfwgy** [RuffianZhong/RWidgetHelper#95]
* mTextColorPressed未设置取值的优先级是：mTextColorChecked>mTextColorSelected>mTextColorNormal
* mBackgroundColorPressed(mBackgroundColorPressedArray)未设置取值的优先级是：mBackgroundColorChecked>mBackgroundColorSelected>mBackgroundColorNormal
* mHasPressedBorderWidth
* mHasPressedBorderColor
* 其它等等
 
大部分的默认值，都是取的Normal对应的值。  只有极个别的属性是按照上述规则取的:Checked>Selected>Normal。不知道是考虑到什么场景？

1. 在我这个应用中遇到这个问题了，按压下去的特效特别丑。
2. 默认值的处理应该有一个统一的规则会好一点。不满足开发者需求，自己去设置对应的值即可。

**Comment by scsfwgy** [comment]
还有一点，如果Normal更新，理论上也要更新Pressed（没有设置过值，默认值不算）对应的值。不然按压效果就是原来的Normal值，也会很冲。

**Comment by RuffianZhong** [comment]
support.v0.0.4/androidx.v0.0.4 版本开始已修改
