### ISSUE TITLE
checked相关属性bug

### ISSUE THREAD

**Issue by TianGuisen** [RuffianZhong/RWidgetHelper#98]
```
        <com.ruffian.library.widget.RRadioButton
            android:button="@null"
            app:background_checked="#BB1E0A"
            app:background_normal="#F5F5F5"
            app:icon_checked_right="@drawable/comment1"
            app:icon_normal_right="@drawable/comment11"
            app:text_color_checked="@color/white"
            app:text_color_normal="@color/c_333" />
```
一个RadioGroup中有多个类似上面的控件,从未选中手指按下还没有松开的时候，此时显示的状态是
  app:background_checked="#BB1E0A"
  app:icon_normal_right="@drawable/comment11"
app:text_color_checked="@color/white"

松开后， app:icon_normal_right="@drawable/comment11"才会切换到  app:icon_checked_right="@drawable/comment1"状态显示。

不知道这算是icon的bug还是    background和textcolor的bug

**Comment by scsfwgy** [comment]
用最新版本再试试
